version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: project_open_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: alpine:latest
    container_name: project_open_web
    command: tail -f /dev/null
    depends_on:
      - db
volumes:
  postgres_data:
                 